Repository 0xPolygon/go-ibft, pull requests merged in 2022-10, with the labels that each got.

#27 Introduce property based tests with Rapid + bump go version
  .github/workflows/main.yml
  .gitignore
  core/consensus_test.go
  core/ibft.go
  core/mock_test.go
  core/rapid_test.go
  go.mod
  go.sum
Labels: breaking change, feature

#29 Resolve data races in tests utilizing go routines
  .github/workflows/main.yml
  core/ibft_test.go
  core/mock_test.go
Labels: bug fix

#30 Add golang vulnerabilities checker
  .github/workflows/main.yml
Labels: feature

#32 Integrate goleak to tests
  core/consensus_test.go
  core/core_test.go
  core/ibft_test.go
  core/rapid_test.go
  go.mod
  go.sum
  messages/event_manager_test.go
  messages/event_subscription_test.go
  messages/helpers_test.go
  messages/messages_test.go
Labels: feature

#31 Introduce drop property tests
  core/drop_test.go
  core/helpers_test.go
  go.mod
Labels: feature
