Repository 0xPolygon/go-ibft, pull requests merged in 2022-11, with the labels that each got.

#41 bump golang to 1.19
  .github/workflows/lint.yml
  .github/workflows/main.yml
  go.mod
Labels: feature

#37 Use shuffle in all go test
  .github/workflows/main.yml
Labels: feature

#42 reproducible builds
  .github/workflows/main.yml
  .gitignore
  Makefile
  build/main.go
Labels: feature

#43 Expand `BuildProposal` with current round information
  core/backend.go
  core/consensus_test.go
  core/helpers_test.go
  core/ibft.go
  core/ibft_test.go
  core/mock_test.go
  core/rapid_test.go
Labels: breaking change

#39 Move logic for quorum check to the backend
  .github/workflows/main.yml
  core/backend.go
  core/consensus_test.go
  core/drop_test.go
  core/helpers_test.go
  core/ibft.go
  core/ibft_test.go
  core/mock_test.go
  core/rapid_test.go
  messages/event_manager.go
  messages/event_manager_test.go
  messages/event_subscription.go
  messages/event_subscription_test.go
  messages/messages.go
  messages/messages_test.go
Labels: breaking change, feature

#40 update linters
  .github/workflows/lint.yml
  .github/workflows/main.yml
  .golangci.yml
  Makefile
  build/main.go
Labels: feature

#45 Minor fixes in ibft and tests
  .golangci.yml
  core/ibft.go
  core/mock_test.go
  core/rapid_test.go
Labels: bug fix, bug

#44 Add rapid test with bad proposal coming from byzantine node
  .github/workflows/main.yml
  .golangci.yml
  core/consensus_test.go
  core/ibft.go
  core/ibft_test.go
  core/mock_test.go
  core/rapid_test.go
Labels: feature

#48 EVM-220 TestClusterBlockSync/BLS fails in voting power branch
  core/ibft.go
  core/ibft_test.go
  core/mock_test.go
  messages/messages.go
  messages/messages_test.go
Labels: bug fix

#47 Added per round event-based setup in rapid tests
  core/consensus_test.go
  core/mock_test.go
  core/rapid_test.go
Labels: feature
