Repository 0xPolygon/go-ibft, pull requests merged in 2023-01, with the labels that each got.

#56 Byzantine tests
  core/byzantine_test.go
  core/helpers_test.go
Labels: audit

#58 Suggestion 4: Add Fault Tests
  core/drop_test.go
  core/helpers_test.go
Labels: audit

#52 Fix wrong selection of proposed block from previous round in non-zero…
  core/ibft.go
  core/ibft_test.go
  core/mock_test.go
  messages/messages.go
  messages/messages_test.go
Labels: bug fix, audit

#53 Remove redundant code and Add Safe check in bulding committed seals
  core/ibft.go
  messages/helpers.go
  messages/helpers_test.go
Labels: bug fix, audit

#55 [PoC] Fix hash calculation for proposal
  Makefile
  core/backend.go
  core/byzantine_test.go
  core/consensus_test.go
  core/drop_test.go
  core/helpers_test.go
  core/ibft.go
  core/ibft_test.go
  core/mock_test.go
  core/rapid_test.go
  core/state.go
  go.mod
  go.sum
  messages/event_manager.go
  messages/helpers.go
  messages/helpers_test.go
  messages/proto/messages.pb.go
  messages/proto/messages.proto
Labels: bug fix

#54 Improve Code Comments
  core/backend.go
  core/byzantine_test.go
  core/drop_test.go
  core/ibft.go
  core/ibft_test.go
  core/mock_test.go
Labels: audit
